### PR TITLE
Refresh container list after making a status change

### LINKED ISSUE #12: Automatically refresh after running a context menu command
I have auto refresh set to off, so when I run a context menu command, nothing in the UI changes until I manually hit refresh. Regardless of auto refresh configuration, the UI should update after executing a command.

### PR DESCRIPTION
**Pull request by aharpervc**
Fixes #12

### CODE REVIEW

**Comment by aharpervc** [comment]
Pretty sure this is all that is needed?

**Comment by formulahendry** [comment]
@aharpervc Executor.runInTerminal() is an async function, so this change will not take effect.

**Comment by aharpervc** [comment]
I see. What's the fix?

**Comment by formulahendry** [comment]
There need more code refactoring without using `runInTerminal`. One option is using `child_process.execSync` API.  One thing I am curious is that why you would like disable the auto-refresh. Is there any side effect of it? With the auto-refresh, we don't need to refresh container after any operation is done. 😄

**Comment by aharpervc** [comment]
I often keep "Docker for Win/Mac" turned off, so this creates problems with the cli tool can't talk to that service. Also I run quite a few instances of VS Code so that's a lot of notices and failing processes spawning all the time. Plus, I don't often change container state except when developing inside of VS Code, so it's not like the auto refresh would tell me about something I didn't just do manually.

**Comment by formulahendry** [comment]
Thanks @aharpervc for the detailed info. In that case, it seems that the only side effect of auto-refresh is that it will show error message for each VS Code instance. Therefore, a quick turnaround is to provide an option to allow user to let extension not show the error message. What's your thought about this?

**Comment by aharpervc** [comment]
Sure, that would help. You'd also have processes needlessly running and dying in the background unceasingly, but that's probably not that big of a deal.

**Comment by formulahendry** [comment]
#16 is opened. Closing this PR. Would you like to send a new PR to implement #16 or let me implement that?

**Comment by aharpervc** [comment]
I have no idea how notifications work, so go for it.

**Pull request closed without merging**
